export const faultData = [
  {
    id: 1,
    brand: "Volkswagen",
    model: "Golf 1.4 TSI",
    year: "2013-2019",
    yearMin: 2013,
    yearMax: 2019,
    motorType: "Benzin",
    fault: "Zincir seti soğuk çalıştırmada ses",
    description: "Zincir seti soğuk çalıştırmada ses",
    symptoms: "Şakırtı sesi, motor arıza lambesi, geç çalışma",
    checkTip: "Soğuk çalıştırmada zincir sesi var mı?",
    risk: "YÜKSEK",
    costMin: 19000,
    costMax: 45000,
    avgCost: 32000,
    kmDisplay: "60.000 km+",
    kmMin: 60000,
    reportCount: 88,
    category: "Motor",
  },
  {
    id: 2,
    brand: "Volkswagen",
    model: "Passat 2.0 TDI",
    year: "2015-2020",
    yearMin: 2015,
    yearMax: 2020,
    motorType: "Dizel",
    fault: "Turbo hortumunda yağ kaçırması",
    description: "Turbo hortumunda yağ kaçırması",
    symptoms: "Yağ lekesi, güç kaybı, mavi duman",
    checkTip: "Turbo hortumlarında yağ sızıntısı var mı?",
    risk: "ORTA",
    costMin: 2500,
    costMax: 8000,
    avgCost: 5000,
    kmDisplay: "100.000 km+",
    kmMin: 100000,
    reportCount: 67,
    category: "Motor",
  },
  {
    id: 3,
    brand: "Renault",
    model: "Megane 1.5 DCI",
    year: "2016-2021",
    yearMin: 2016,
    yearMax: 2021,
    motorType: "Dizel",
    fault: "EDC şanzımanda kalkış titremesi",
    description: "EDC şanzımanda kalkış titremesi",
    symptoms: "Kalkışta titreme, vuruntu, atlama",
    checkTip: "EDC şanzımanda kalkış esnasında titreme var mı?",
    risk: "ORTA",
    costMin: 8000,
    costMax: 20000,
    avgCost: 14000,
    kmDisplay: "120.000 km+",
    kmMin: 80000,
    reportCount: 72,
    category: "Şanzıman",
  },
  {
    id: 4,
    brand: "Renault",
    model: "Talisman 1.6 DCI",
    year: "2016-2022",
    yearMin: 2016,
    yearMax: 2022,
    motorType: "Dizel",
    fault: "Enjektör seti arızası",
    description: "Enjektör seti arızası",
    symptoms: "Motor titremesi, güç kaybı, aşırı yakıt tüketimi",
    checkTip: "Rölantide motor düzensiz çalışıyor mu?",
    risk: "YÜKSEK",
    costMin: 25000,
    costMax: 55000,
    avgCost: 40000,
    kmDisplay: "150.000 km+",
    kmMin: 100000,
    reportCount: 54,
    category: "Motor",
  },
  {
    id: 5,
    brand: "BMW",
    model: "320i F30",
    year: "2012-2018",
    yearMin: 2012,
    yearMax: 2018,
    motorType: "Benzin",
    fault: "Zincir gergi mekanizması aşınması",
    description: "Zincir gergi mekanizması aşınması",
    symptoms: "Motor tıkırtısı, yağ basınç uyarısı, performans düşüşü",
    checkTip: "Motor soğukken tıkırtı sesi geliyor mu?",
    risk: "YÜKSEK",
    costMin: 28000,
    costMax: 42000,
    avgCost: 35000,
    kmDisplay: "80.000 km+",
    kmMin: 80000,
    reportCount: 287,
    category: "Motor",
  },
  {
    id: 6,
    brand: "BMW",
    model: "520d G30",
    year: "2017-2022",
    yearMin: 2017,
    yearMax: 2022,
    motorType: "Dizel",
    fault: "AdBlue dozaj ünitesi arızası",
    description: "AdBlue dozaj ünitesi arızası",
    symptoms: "Motor check lambesi, çalışma sayacı, motor start yasağı",
    checkTip: "AdBlue uyarı lambesi yakıyor mu?",
    risk: "YÜKSEK",
    costMin: 22000,
    costMax: 42000,
    avgCost: 32000,
    kmDisplay: "80.000 km+",
    kmMin: 80000,
    reportCount: 189,
    category: "Egzoz",
  },
  {
    id: 7,
    brand: "Ford",
    model: "Focus PowerShift",
    year: "2011-2018",
    yearMin: 2011,
    yearMax: 2018,
    motorType: "Benzin",
    fault: "Çift kavrama titreşim sorunu",
    description: "Çift kavrama titreşim sorunu",
    symptoms: "Düşük viteste titreme, sarsıntı, ani vites geçişi",
    checkTip: "1-2 vites geçişinde sarsıntı var mı?",
    risk: "YÜKSEK",
    costMin: 25000,
    costMax: 55000,
    avgCost: 38000,
    kmDisplay: "40.000 km+",
    kmMin: 40000,
    reportCount: 456,
    category: "Şanzıman",
  },
  {
    id: 8,
    brand: "Toyota",
    model: "Corolla E210",
    year: "2019-2023",
    yearMin: 2019,
    yearMax: 2023,
    motorType: "Hibrit",
    fault: "CVT şanzıman vınlama sesi",
    description: "CVT şanzıman vınlama sesi",
    symptoms: "Hızlanmada vınlama, kayma hissi, konfor kaybı",
    checkTip: "Hız artışında sürekli vınlama var mı?",
    risk: "DÜŞÜK",
    costMin: 5000,
    costMax: 12000,
    avgCost: 8000,
    kmDisplay: "30.000 km+",
    kmMin: 30000,
    reportCount: 89,
    category: "Şanzıman",
  },
  {
    id: 9,
    brand: "Fiat",
    model: "Egea 1.3 MultiJet",
    year: "2015-2023",
    yearMin: 2015,
    yearMax: 2023,
    motorType: "Dizel",
    fault: "Turbo aktuatör arızası",
    description: "Turbo aktuatör arızası",
    symptoms: "Check lambesi, güç kaybı, limp mode",
    checkTip: "Ani gaz verişinde güç kaybı yaşanıyor mu?",
    risk: "ORTA",
    costMin: 10000,
    costMax: 22000,
    avgCost: 15000,
    kmDisplay: "80.000 km+",
    kmMin: 80000,
    reportCount: 267,
    category: "Motor",
  },
  {
    id: 10,
    brand: "Volkswagen",
    model: "Passat B8 DSG",
    year: "2015-2019",
    yearMin: 2015,
    yearMax: 2019,
    motorType: "Benzin",
    fault: "DSG şanzıman sarsıntısı",
    description: "DSG şanzıman sarsıntısı",
    symptoms: "Düşük hızda sarsıntı, titreşim, vites gecikmesi",
    checkTip: "Düşük hızda vites geçerken sarsıntı var mı?",
    risk: "YÜKSEK",
    costMin: 30000,
    costMax: 60000,
    avgCost: 45000,
    kmDisplay: "60.000 km+",
    kmMin: 60000,
    reportCount: 342,
    category: "Şanzıman",
  },
  {
    id: 11,
    brand: "Mercedes",
    model: "C180 W205",
    year: "2014-2021",
    yearMin: 2014,
    yearMax: 2021,
    motorType: "Benzin",
    fault: "Valf kapağı contası yağ kaçağı",
    description: "Valf kapağı contası yağ kaçağı",
    symptoms: "Motor üstünde yağ birikintisi, yanık kokusu, yağ azalması",
    checkTip: "Motor üstünde yağ izi görülüyor mu?",
    risk: "ORTA",
    costMin: 12000,
    costMax: 25000,
    avgCost: 18000,
    kmDisplay: "70.000 km+",
    kmMin: 70000,
    reportCount: 178,
    category: "Motor",
  },
  {
    id: 12,
    brand: "Hyundai",
    model: "Tucson 2.0 CRDi",
    year: "2015-2020",
    yearMin: 2015,
    yearMax: 2020,
    motorType: "Dizel",
    fault: "DPF filtresi tıkanması",
    description: "DPF filtresi tıkanması",
    symptoms: "Güç kaybı, motor check, rejenerasyon hatası",
    checkTip: "Şehir içi kullanımda check lambesi yakıyor mu?",
    risk: "YÜKSEK",
    costMin: 18000,
    costMax: 35000,
    avgCost: 25000,
    kmDisplay: "60.000 km+",
    kmMin: 60000,
    reportCount: 203,
    category: "Egzoz",
  },
  {
    id: 13,
    brand: "Audi",
    model: "A3 1.4 TFSI",
    year: "2013-2020",
    yearMin: 2013,
    yearMax: 2020,
    motorType: "Benzin",
    fault: "Aşırı yağ tüketimi",
    description: "Aşırı yağ tüketimi",
    symptoms: "Mavi duman, yağ azalması, egzozdan koku",
    checkTip: "1.000 km'de 0.5L'den fazla yağ tüketiyor mu?",
    risk: "YÜKSEK",
    costMin: 15000,
    costMax: 30000,
    avgCost: 22000,
    kmDisplay: "70.000 km+",
    kmMin: 70000,
    reportCount: 245,
    category: "Motor",
  },
  {
    id: 14,
    brand: "Peugeot",
    model: "3008 EAT8",
    year: "2017-2022",
    yearMin: 2017,
    yearMax: 2022,
    motorType: "Benzin",
    fault: "EAT8 şanzıman sarsıntısı",
    description: "EAT8 şanzıman sarsıntısı",
    symptoms: "Düşük hızda sarsıntı, gecikme, yazılım hatası",
    checkTip: "İlk vites geçişinde takılma hissediliyor mu?",
    risk: "ORTA",
    costMin: 12000,
    costMax: 30000,
    avgCost: 20000,
    kmDisplay: "50.000 km+",
    kmMin: 50000,
    reportCount: 167,
    category: "Şanzıman",
  },
  {
    id: 15,
    brand: "Dacia",
    model: "Duster 1.6",
    year: "2018-2023",
    yearMin: 2018,
    yearMax: 2023,
    motorType: "Benzin",
    fault: "Rot başı erken aşınması",
    description: "Rot başı erken aşınması",
    symptoms: "Direksiyon titremesi, düzensiz lastik aşınması, ses",
    checkTip: "Hız tümseklerinde direksiyon titriyor mu?",
    risk: "DÜŞÜK",
    costMin: 2000,
    costMax: 6000,
    avgCost: 3500,
    kmDisplay: "40.000 km+",
    kmMin: 40000,
    reportCount: 112,
    category: "Süspansiyon",
  },
];

export const brands = [...new Set(faultData.map(f => f.brand))].sort();
export const categories = [...new Set(faultData.map(f => f.category))].sort();
export const motorTypes = [...new Set(faultData.map(f => f.motorType))].sort();
export const riskLevels = ["YÜKSEK", "ORTA", "DÜŞÜK"];
