export const popularModelTags = [
  'Fiat Egea',
  'Renault Clio',
  'Renault Megane Sedan',
  'Toyota Corolla',
  'Honda Civic',
  'Volkswagen Passat',
  'Dacia Duster',
  'Hyundai i20',
  'Ford Focus',
  'Volkswagen Golf',
  'Toyota C-HR',
  'Peugeot 3008',
  'Nissan Qashqai',
  'Togg T10X',
  'Volkswagen Polo',
  'Tesla Model Y',
  'BYD Seal U',
  'Dacia Sandero Stepway',
  'Volkswagen Taigo',
  'Volkswagen T-Cross',
  'Ford Transit',
  'Fiat Doblo',
  'Citroen Berlingo',
  'Opel Combo',
  'Peugeot Rifter',
  'Ford Transit Custom',
  'Volkswagen Caddy',
  'Fiat Ducato',
  'Fiat Scudo',
];
